name: Rust

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install/update Rust
        shell: bash
        run: rustup toolchain install nightly --component rustfmt

      - name: Formatting
        shell: bash
        run: cargo +nightly fmt -- --check

  checks:
    name: Tests and Lints
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install/update Rust
        shell: bash
        run: |
          rustup update
          rustup show # Uses rust-toolchain.toml file to install the correct version and components.

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-make

      - name: Caching
        uses: Swatinem/rust-cache@v2

      - name: Run the CI checks
        shell: bash
        run: cargo make stable-ci
